import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cine Rental | Learn with Sumit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`${inter.className} font-[Sora] text-dark bg-white dark:text-white dark:bg-body`}
        >
          {children}
        </body>
        <div id="modal-root-content" />
      </Provider>
    </html>
  );
}
